channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pandas
  - numpy=1.23.5
  - numba=0.57.1
  - pip:
    - xmltodict
    - requests
    - requests_cache
    - tqdm
    - pyteomics
